/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutTheBoxFrame.java
 *
 * Created on May 14, 2009, 4:41:42 PM
 */

package interfaz;

/**
 *
 * @author alos
 */
public class AboutTheBoxWindow extends javax.swing.JFrame {

    /** Creates new form AboutTheBoxFrame */
    public AboutTheBoxWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/iconos/serbia.png"))); // NOI18N

        jLabel2.setText("<html>Sistema de Extracci&oacute;n de Referencias Bibliogr&aacute;ficas con Inteligencia Artificial</html>");

        jLabel3.setText("<html>\nDesarollado por:<br> \nSergio Eduardo F&eacute;lix Aparicio - <a href=\"mailto:alosii@gmail.com\">alosii@gmail.com</a><br >\nOswaldo Guti&eacute;rrez Esamilla - <a href=\"mailto:oswaldozenky@gmail.com\">oswaldozenky@gmail.com</a><br >\nLuis Enrique Garc&iacute;a Zetina - <a href=\"mailto:luisgar1437@hotmail.com\">luisgar1437@hotmail.com</a><br >\nGustavo Enrique Vargas Nava - <a href=\"mailto:rayhare@gmail.com\">rayhare@gmail.com</a><br >\n<br>\nDise&ntilde;o por: <br>\n Jorge Alberto Cid Cruz - <a href=\"mailto:jorge.cida@gmail.com\">jorge.cida@gmail.com</a><br >\n<br>\n<FONT SIZE=\"-1\"><i>SERBIA is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License.\n <br>\nSERBIA is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.</i></FONT> \n </html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 463, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 565, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28)
                .add(jLabel2)
                .add(29, 29, 29)
                .add(jLabel3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.dispose();
    }//GEN-LAST:event_formMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutTheBoxWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
