/*
 *
 * This file is part of Louhi.

    Louhi is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    Louhi is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Louhi.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * ReviewWindow.java
 *
 * Created on Apr 22, 2009, 11:53:21 AM
 */

package interfaz;

import java.util.LinkedList;
import javax.swing.table.TableColumn;
import modelo.TemporalReference;
import modelo.Clasificacion;
import javax.swing.table.TableModel;
/**
 *
 * @author alos
 */
public class ReviewWindow extends javax.swing.JFrame {
    control.AppController control;
    LinkedList<TemporalReference> citList= new LinkedList<TemporalReference>();
    /** Creates new form ReviewWindow */
    public ReviewWindow(control.AppController unControl) {
        initComponents();
        this.control = unControl;
        TableColumn column = null;
        for (int i = 0; i <= 8; i++) {
            column = this.tablaResumenCita.getColumnModel().getColumn(i);
            if(i==0)
               column.setPreferredWidth(200);
            if(i==1)
               column.setPreferredWidth(300);
            if(i==2)
               column.setPreferredWidth(150);
            if(i==3)
               column.setPreferredWidth(100);
            if(i==4)
               column.setPreferredWidth(50);
            if(i==5)
               column.setPreferredWidth(50);
            if(i==6)
               column.setPreferredWidth(150);
            if(i==7)
               column.setPreferredWidth(100);
            if(i==8)
               column.setPreferredWidth(100);
        }
        
        this.setBounds(100, 100, 1000, 400);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResumenCita = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonGuardarFinal = new javax.swing.JButton();
        botonCancelarFinal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nacionalesLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        autocitasLabel = new javax.swing.JLabel();

        setTitle("Resumen de Referencias");
        setAlwaysOnTop(true);

        tablaResumenCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Autores", "Titulo", "Fecha", "Editorial", "Pag.", "Vol.", "Clasificacion", "Lugar", "RevistaRedalyc", "No. Articulo"
            }
        ));
        jScrollPane1.setViewportView(tablaResumenCita);

        jLabel1.setText("Se encontraron las siguientes citas");

        botonGuardarFinal.setText("Guardar");
        botonGuardarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarFinalActionPerformed(evt);
            }
        });

        botonCancelarFinal.setText("Cancelar");
        botonCancelarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarFinalActionPerformed(evt);
            }
        });

        jLabel2.setText("Total de nacionales: ");

        nacionalesLabel.setText("0");

        jLabel3.setText("Total de autocitas:");

        autocitasLabel.setText("0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                            .add(jLabel1)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(botonCancelarFinal)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(botonGuardarFinal))
                            .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(nacionalesLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(autocitasLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .add(747, 747, 747))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(nacionalesLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(autocitasLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(botonGuardarFinal)
                    .add(botonCancelarFinal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarFinalActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarFinalActionPerformed

    private void botonGuardarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarFinalActionPerformed
        this.control.saveCitations(citList);
    }//GEN-LAST:event_botonGuardarFinalActionPerformed

    public void setCitationList(LinkedList<TemporalReference> citList){
        this.citList=citList;
        TableModel modelo = this.tablaResumenCita.getModel();
        int i = 0;
        int counterNacional = 0;
        int counterAutocita = 0;
        for(TemporalReference cit: citList){
            if(cit.getAutors()!=null)
                modelo.setValueAt(cit.getAutors().toString(), i, 0);
            if(cit.getTitle()!=null)
                modelo.setValueAt(cit.getTitle().toString(), i, 1);
            if(cit.getDate()!=null)
                modelo.setValueAt(cit.getDate().getDateWithStatement(), i, 2);
            if(cit.getPublisher()!=null)
                modelo.setValueAt(cit.getPublisher().toString(), i, 3);
            if(cit.getLocation()!=null)
                modelo.setValueAt(cit.getLocation().toString(), i, 7);
            if(cit.getPages()!=null)
                modelo.setValueAt(cit.getPages().toString(), i, 4);
            if(cit.getVolume()!=null)
                modelo.setValueAt(cit.getVolume().toString(), i, 5);
            if(cit.getClasificacion()!=null)
                modelo.setValueAt(cit.getClasificacion().toString(), i, 6);
            if(cit.getIdRevOrigen() != 0)
                modelo.setValueAt(cit.getIdRevOrigen(), i, 8);
            i++;

            if(cit.isIsNacional())
                counterNacional++;
            if(cit.getClasificacion().equals(Clasificacion.AUTOCITA))
                counterAutocita++;
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autocitasLabel;
    private javax.swing.JButton botonCancelarFinal;
    private javax.swing.JButton botonGuardarFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nacionalesLabel;
    private javax.swing.JTable tablaResumenCita;
    // End of variables declaration//GEN-END:variables

}
