/*
 * This file is part of Louhi.

    Louhi is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    Louhi is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Louhi.  If not, see <http://www.gnu.org/licenses/>.
 */

package interfaz;

import control.Db4oConnectionManager;
import control.Db4oLocalConnectionManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import modelo.MetaData;

/**
 *
 * @author oswa
 */
public class UserNameWindow extends javax.swing.JFrame {

    /** Creates new form UserNameWindow */
    public UserNameWindow() {
        initComponents();
        this.BotonAceptarUserName.setEnabled(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    private Interfaz gui;


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFieldUserName = new javax.swing.JTextField();
        BotonAceptarUserName = new javax.swing.JButton();
        BotonCancelarUserName = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nombre de usuario");
        setAlwaysOnTop(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Nombre de usuario:");

        BotonAceptarUserName.setText("Aceptar");
        BotonAceptarUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarUserNameActionPerformed(evt);
            }
        });

        BotonCancelarUserName.setText("Cancelar");
        BotonCancelarUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarUserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(BotonAceptarUserName)
                .addGap(18, 18, 18)
                .addComponent(BotonCancelarUserName)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCancelarUserName)
                    .addComponent(BotonAceptarUserName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        TextFieldUserName.getDocument().addDocumentListener(new DocumentListener() {

            public void insertUpdate(DocumentEvent arg0) {
                BotonAceptarUserName.setEnabled(true);
            }

            public void removeUpdate(DocumentEvent arg0) {
                if(!TextFieldUserName.getText().equals(""))
                    BotonAceptarUserName.setEnabled(true);
                else
                    BotonAceptarUserName.setEnabled(false);
            }

            public void changedUpdate(DocumentEvent arg0) {
                BotonAceptarUserName.setEnabled(true);
            }
        });
    }//GEN-LAST:event_formComponentShown

    private void BotonCancelarUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarUserNameActionPerformed
        Db4oConnectionManager.closeDB();
        Db4oLocalConnectionManager.closeDB();
        System.exit(0);
    }//GEN-LAST:event_BotonCancelarUserNameActionPerformed

    private void BotonAceptarUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarUserNameActionPerformed
        String userName = this.TextFieldUserName.getText();
        System.out.println(userName);
        MetaData md = new MetaData();
        md.setUserName(userName);
        this.setVisible(false);
        //this.gui = new Interfaz(this);
        gui.setVisible(true);
    }//GEN-LAST:event_BotonAceptarUserNameActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserNameWindow().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptarUserName;
    private javax.swing.JButton BotonCancelarUserName;
    private javax.swing.JTextField TextFieldUserName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
